### ISSUE TITLE
void setup or loop error at sensor.ino

### ISSUE THREAD

**Issue by kevindiazp** [KebabLord/esp_to_python#1]
Hello KebabLord, can I ask some question?
Before that sorry if it interferes with your activities now.

When I insert code at file sensor.ino, there's some error like this

sensor:31:16: error: a function-definition is not allowed here before '{' token

   void setup() {

                ^

sensor:119:3: error: expected '}' at end of input

   }

   ^

exit status 1
a function-definition is not allowed here before '{' token

Might help me to solve this problem if you can...

Oh, and there's my code to insert to sensor.ino.
You can check link here
[Code.docx](https://github.com/KebabLord/esp_to_python/files/3043972/Code.docx)

And last question.
for include from my sensor code, where I put the code?

Nt: I don't copy and paste all the code, only from void setup until end.

And sorry for my bad english.

Thanks.

**Comment by KebabLord** [comment]
I'm really sorry for replying it this late!
I updated the code and minimalised it radically. Try it now, it's really much easier to understand now!
The previous code was a soup xP

I'll also simpify it again and create an instructables or youtube guide!

**Comment by kevindiazp** [comment]
That's okay mate...
I will try again later with update code...
Big thanks for this code for my thesis...
God Bless U Always...

**Comment by KebabLord** [comment]
I over simplified it again, I also tested it, it is too much easy to program now. 
Check it again dude :3
