### ISSUE TITLE
LedController Data sending Error

### ISSUE THREAD

**Issue by ubz-rao** [KebabLord/esp_to_python#2]
Hey KebabLord! 

In the **led_controller.py** file after giving the input either ON or OFF to esp the following error arises

**RemoteDisconnected: Remote end closed connection without response**

The data is being sent but each time a value (ON/OFF) is sent to esp the python code terminates with the above error.

It would be a great help if you could look into it.

Thanks

**Comment by sachin-cpp** [comment]
its still not working ..!!!!

**Comment by KebabLord** [comment]
did it work properly after @sachin-cpp's pr  https://github.com/KebabLord/esp2python/pull/3?

**Comment by KebabLord** [comment]
just use http instead of https in python reader code when adding the ESP's IP adress.
